
#ifndef _GUSIDiag_
#define _GUSIDiag_

#include <sys/cdefs.h>
#include <stdarg.h>
#include <string.h>

#include <MacTypes.h>

__BEGIN_DECLS

extern char * GUSI_diag_log;

bool GUSI_pos(const char * file, int line);
bool GUSI_log(const char * format, ...);
bool GUSI_break(const char * format, ...);


#define GUSI_DIAG_RECKLESS	0
#define GUSI_DIAG_RELAXED	1
#define GUSI_DIAG_CAUTIOUS	2
#define GUSI_DIAG_PARANOID	3

#ifndef GUSI_DIAG
#define GUSI_DIAG GUSI_DIAG_PARANOID
#endif
#ifndef GUSI_LOG_POS
#define GUSI_LOG_POS	0
#endif
#ifndef GUSI_MESSAGE_LEVEL 
#define GUSI_MESSAGE_LEVEL	3
#endif


#if GUSI_LOG_POS
#define GUSI_POS	GUSI_pos(__FILE__, __LINE__)
#define GUSI_LOG	GUSI_POS || GUSI_log
#else
#define GUSI_LOG	GUSI_log
#endif
#define GUSI_BREAK	GUSI_break

#if GUSI_DIAG == GUSI_DIAG_RECKLESS

#define GUSI_ASSERT_INTERNAL(COND, ARGLIST)		true
#define GUSI_ASSERT_CLIENT(COND, ARGLIST)		true
#define GUSI_ASSERT_EXTERNAL(COND, ARGLIST)		(COND)
#define GUSI_SASSERT_INTERNAL(COND, MSG)		true
#define GUSI_SASSERT_CLIENT(COND, MSG)			true
#define GUSI_SASSERT_EXTERNAL(COND, MSG)		(COND)

#elif GUSI_DIAG == GUSI_DIAG_RELAXED

#define GUSI_ASSERT_INTERNAL(COND, ARGLIST)		true
#define GUSI_ASSERT_CLIENT(COND, ARGLIST)		(COND)
#define GUSI_ASSERT_EXTERNAL(COND, ARGLIST)		(COND)
#define GUSI_SASSERT_INTERNAL(COND, MSG)		true
#define GUSI_SASSERT_CLIENT(COND, MSG)			(COND)
#define GUSI_SASSERT_EXTERNAL(COND, MSG)		(COND)

#elif GUSI_DIAG == GUSI_DIAG_CAUTIOUS

#define GUSI_ASSERT_INTERNAL(COND, ARGLIST)		((COND) || GUSI_LOG ARGLIST)
#define GUSI_ASSERT_CLIENT(COND, ARGLIST)		((COND) || GUSI_LOG ARGLIST)
#define GUSI_ASSERT_EXTERNAL(COND, ARGLIST)		(COND)
#define GUSI_SASSERT_INTERNAL(COND, MSG)		((COND) || GUSI_LOG ("%s", MSG))
#define GUSI_SASSERT_CLIENT(COND, MSG)			((COND) || GUSI_LOG ("%s", MSG))
#define GUSI_SASSERT_EXTERNAL(COND, MSG)		(COND)

#elif GUSI_DIAG == GUSI_DIAG_PARANOID

#define GUSI_ASSERT_INTERNAL(COND, ARGLIST)		((COND) || GUSI_BREAK ARGLIST)
#define GUSI_ASSERT_CLIENT(COND, ARGLIST)		((COND) || GUSI_LOG ARGLIST)
#define GUSI_ASSERT_EXTERNAL(COND, ARGLIST)		((COND) || GUSI_LOG ARGLIST)
#define GUSI_SASSERT_INTERNAL(COND, MSG)		((COND) || GUSI_BREAK ("%s", (MSG)))
#define GUSI_SASSERT_CLIENT(COND, MSG)			((COND) || GUSI_LOG ("%s", MSG))
#define GUSI_SASSERT_EXTERNAL(COND, MSG)		((COND) || GUSI_LOG ("%s", MSG))

#else
#error "GUSI_DIAG defined to illegal value: " GUSI_DIAG
#endif

#define GUSI_CASSERT_INTERNAL(COND)	\
	GUSI_SASSERT_INTERNAL(COND, "(" #COND ") -- assertion failed.\n" )
#define GUSI_CASSERT_CLIENT(COND)	\
	GUSI_SASSERT_CLIENT(COND,   "(" #COND ") -- assertion failed.\n" )
#define GUSI_CASSERT_EXTERNAL(COND)	\
	GUSI_SASSERT_EXTERNAL(COND, "(" #COND ") -- assertion failed.\n" )
#define GUSI_MESSAGE1(ARGLIST)		\
	GUSI_ASSERT_EXTERNAL(GUSI_MESSAGE_LEVEL>1, ARGLIST)
#define GUSI_SMESSAGE1(MSG)			\
	GUSI_SASSERT_EXTERNAL(GUSI_MESSAGE_LEVEL>1, MSG)
#define GUSI_MESSAGE2(ARGLIST)		\
	GUSI_ASSERT_EXTERNAL(GUSI_MESSAGE_LEVEL>2, ARGLIST)
#define GUSI_SMESSAGE2(MSG)			\
	GUSI_SASSERT_EXTERNAL(GUSI_MESSAGE_LEVEL>2, MSG)
#define GUSI_MESSAGE3(ARGLIST)		\
	GUSI_ASSERT_EXTERNAL(GUSI_MESSAGE_LEVEL>3, ARGLIST)
#define GUSI_SMESSAGE3(MSG)			\
	GUSI_SASSERT_EXTERNAL(GUSI_MESSAGE_LEVEL>3, MSG)
#define GUSI_MESSAGE4(ARGLIST)		\
	GUSI_ASSERT_EXTERNAL(GUSI_MESSAGE_LEVEL>4, ARGLIST)
#define GUSI_SMESSAGE4(MSG)			\
	GUSI_SASSERT_EXTERNAL(GUSI_MESSAGE_LEVEL>4, MSG)
#define GUSI_MESSAGE5(ARGLIST)		\
	GUSI_ASSERT_EXTERNAL(GUSI_MESSAGE_LEVEL>5, ARGLIST)
#define GUSI_SMESSAGE5(MSG)			\
	GUSI_SASSERT_EXTERNAL(GUSI_MESSAGE_LEVEL>5, MSG)
#define GUSI_MESSAGE(ARGLIST)	GUSI_MESSAGE3(ARGLIST)
#define GUSI_SMESSAGE(MSG)		GUSI_SMESSAGE3(MSG)

__END_DECLS

#endif /* _GUSIDiag_ */
